### ISSUE TITLE
Cannot handle, expecting different type of instance

### ISSUE THREAD

**Issue by konstantinrachev** [filp/whoops#303] opened 2015-08-07 16:16 UTC
As PHP 7 beta 3 was released this one was thrown immediately after updating. 

```php
Whoops\Exception\ErrorException thrown with message "Uncaught TypeError: Argument 1 passed to Whoops\Run::handleException() must be an instance of Exception, instance of ParseError given in C:\Apache24\htdocs\quest-ismena\vendor\filp\whoops\src\Whoops\Run.php:233
Stack trace:
#0 [internal function]: Whoops\Run->handleException(Object(ParseError))
#1 {main}
  thrown"

Stacktrace:
#0  in ...\vendor\filp\whoops\src\Whoops\Run.php:233
```
...\vendor\filp\whoops\src\Whoops\Run.php:233 contains the following:
```php
public function handleException(Exception $exception) { ... }
```

**Comment by denis-sokolov** [comment] 2015-08-07 16:31
Thank you for reporting. This is a duplicate of #284.

**Closed by denis-sokolov** 2015-08-07 16:31 UTC

**Comment by empiricalx** [comment] 2017-01-21 04:43
I got the same error while switching from mysqli to PDO, this error even so is telling your that is on line 233 of Run.php, it seems that is something else that is causing the problem.

**Comment by staabm** [comment] 2017-01-21 07:44
@empiricalx as the inital issue discussed here is from 2015 please open a new issue with more details and at best some code how to reproduce. Also provide information on which whoops/php version you are using
