### ISSUE TITLE
Dependent on cloudflare

### ISSUE THREAD

**Issue by KuenzelIT** [filp/whoops#264] opened 2015-02-22 03:13 UTC
There are two cloudflare usages in layout.html.php:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.js"></script>
```

I don't like the fact that I am dependent on cloudflare. What do you think about this?

**Comment by denis-sokolov** [comment] 2015-02-22 08:20
Duplicate of #251. Please discuss there.

**Closed by denis-sokolov** 2015-02-22 08:20 UTC
