### ISSUE TITLE
PrettyPageHandler - code highlight breaking

### ISSUE THREAD

**Issue by acidjazz** [filp/whoops#435] opened 2016-08-06 22:38 UTC
It's breaking around comments

![image](https://cloud.githubusercontent.com/assets/967369/17459425/dd9bd310-5beb-11e6-986d-9e2c4993507b.png)

**Comment by prisis** [comment] 2016-08-06 23:17
Hey :), duplicate of https://github.com/filp/whoops/issues/426, take the search first, next time

**Comment by acidjazz** [comment] 2016-08-06 23:47
@prisis I did, and saw those, but they're all closed, so I assume they're fixed?

**Comment by prisis** [comment] 2016-08-06 23:52
@acidjazz if you take a look in https://github.com/filp/whoops/issues/214, we didn't find a good solution to fix this...

**Comment by acidjazz** [comment] 2016-08-06 23:56
I see @prisis , interesting, what is being used to highlight php code?

**Comment by prisis** [comment] 2016-08-07 00:02
whoops use https://github.com/filp/whoops/blob/a9d17d13aca43d9b39aa5073d64ff4086b955946/src/Whoops/Resources/js/whoops.base.js#L15

**Comment by acidjazz** [comment] 2016-08-07 00:03
@Prisis looks like https://github.com/google/code-prettify

**Comment by acidjazz** [comment] 2016-08-07 01:55
I've written a fix for this:

![image](https://cloud.githubusercontent.com/assets/967369/17460003/2741eafc-5c07-11e6-9f0b-ad9ecd2a646a.png)

What it does is allow the prettifier to highlight the entire file, then i set a maximum height on the div and scroll to the line of code, this allows also the functionality to browser the entire file.

Let me know what you think I'll create a pull request.

**Comment by acidjazz** [comment] 2016-08-07 02:51
@prisis 
https://github.com/filp/whoops/pull/436

**Closed** 2016-08-08 06:27 UTC

**Comment by filips123** [comment] 2018-10-28 17:18
@acidjazz @denis-sokolov This still sometimes not work. See #588 and google/code-prettify#553 for details.
