### ISSUE TITLE
Collaborate with PsySH and make REPL

### ISSUE THREAD

**Issue by filips123** [filp/whoops#585] opened 2018-07-06 10:21 UTC
You could collaborate with [PsySH](https://github.com/bobthecow/psysh) and make online REPL for PHP. See https://github.com/bobthecow/psysh/issues/505 and https://github.com/bobthecow/psysh/issues/505#issuecomment-402972140.

I know there is old issue for REPL in Whoops (#42), but it is very old and closed.

**Comment by jens1o** [comment] 2018-07-06 16:37
That would be awesome!

**Comment by filips123** [comment] 2018-08-01 18:10
Maybe you could use [Web Console](https://github.com/nickola/web-console) to access [PsySH](https://github.com/bobthecow/psysh).

**Comment by denis-sokolov** [comment] 2019-06-21 10:01
This is a duplicate of #42.

**Closed by denis-sokolov** 2019-06-21 10:01 UTC

**Comment by filips123** [comment] 2019-06-21 10:31
@denis-sokolov Can you reopen #42 so it would receive more attention?

**Comment by denis-sokolov** [comment] 2019-06-21 10:32
On this project a GitHub issue is a poor medium for a wishlist of features. It’s on the wiki: https://github.com/filp/whoops/wiki/Possible-features-to-add
