### ISSUE TITLE
Line does not highlight on initial load

### ISSUE THREAD

**Issue by Vivalldi** [filp/whoops#370] opened 2016-01-19 17:58 UTC
When whoops handles an error the line is not highlighted right away (the css class is not applied). You have to click on the error itself in order to get the highlight to show.

No highlight
http://i.imgur.com/vDE5bc9.png

With highlight after clicking error.
http://i.imgur.com/hPJmiAg.png

**Comment by staabm** [comment] 2016-01-19 18:02
Duplicate of https://github.com/filp/whoops/issues/359?

**Comment by Vivalldi** [comment] 2016-01-19 18:13
Yep. Got it.

**Comment by denis-sokolov** [comment] 2016-01-19 18:20
I don't think it's a duplicate. #359 is fixed and closed, this is something new. @Vivalldi, please confirm you're using the latest version of Whoops.

**Comment by Vivalldi** [comment] 2016-01-19 19:15
Using 2.0.0-alpha2

**Comment by denis-sokolov** [comment] 2016-01-19 19:21
Try 2.0.0, release version!

**Comment by Vivalldi** [comment] 2016-01-19 19:22
Yep. Once our team pushes that into release we'll be good to go. Thanks

**Comment by youssefhad** [comment] 2016-01-19 21:18
i think it the same, instead of three red lines it show only one grey line

**Closed** 2016-01-20 04:14 UTC
