### ISSUE TITLE
Email the pretty-printed error as an html attachment; show generic friendly error page

### ISSUE THREAD

**Issue by robertlagrant** [filp/whoops#261] opened 2015-02-05 12:03 UTC
As an enhancement to the current project, instead of showing the end-user an unfriendly error page (beautiful yes, but still full of code), could the pretty error render to an html attachment that gets emailed to an admin mailbox, and the user just sees a general-purpose ("something went wrong, sorry!") error?

This is just a specific case; I suppose the general one would be being able to interact with the error just before it gets sent to the screen and being able to push it to a deduping error log system, emailing it somewhere, etc etc.

**Comment by denis-sokolov** [comment] 2015-02-05 12:36
You can interact with the error before it gets sent to the screen, use any `Handler`s you want in any order you want. It so happens that the purpose of `PrettyPageHandler` in particular is to print out the pretty page to standard output for the developer to see. You are not supposed to enable this handler on production.

Sending a pretty email is a duplicate of #133.

**Closed by denis-sokolov** 2015-02-05 12:36 UTC

**Comment by robertlagrant** [comment] 2015-02-06 08:24
Glad we agree that it shouldn't be enabled in production; my point was instead of sending it straight to standard out, is there a way to intercept that nice-looking error html so we can bung it into an email attachment.

But anyway, seems as though someone had the same idea. Glad it's on the wishlist.
