### ISSUE TITLE
Version 2.1.0 takes a very long time to render errors

### ISSUE THREAD

**Issue by patroniton** [filp/whoops#401] opened 2016-03-14 21:01 UTC
I'm using Laravel 5.2 and when I call `return parent::render($request, $e);` in the `render` method in `App\Exceptions\Handler.php` it takes a very long time (2-3 minutes) to display the error page. My CPU usage also spikes to 70-80% while it's running.

I'm also using Graham's Laravel Exceptions package [here](https://github.com/GrahamCampbell/Laravel-Exceptions).

If I catch my own exception or return from the method without calling `return parent::render($request, $e);` then the page renders as expected.

This doesn't happen in version 2.0.0, so for now I'm going to keep using that. If you need any more information from me on this issue I'll try my best to provide you with it.

**Comment by GrahamCampbell** [comment] 2016-03-14 21:05
I assume this is because whoops 2.1 is trying to dump some heavy ass objects, and that's taking ages.

**Comment by pelim** [comment] 2016-03-16 16:05
same issue 100% cpu

**Comment by staabm** [comment] 2016-03-16 16:35
could someone create a blackfire.io profile for this slow case?

**Comment by denis-sokolov** [comment] 2016-03-16 16:56
@jonasdt, would you please take a look at this, and whether it is related to #387?

**Comment by jonasdt** [comment] 2016-03-16 20:56
Check #396, for Laravel you can use something like

```php
$handler = new PrettyPageHandler();
$handler->setApplicationNamespaces(['App\\']);
```

It probably makes sense to disable dumping arguments by default.

**Comment by GrahamCampbell** [comment] 2016-03-16 21:23
>  for Laravel you can use something like

That only works if you dump all your code in your application, but does not work if you have a haveily componentized system.

**Comment by GrahamCampbell** [comment] 2016-03-16 21:23
> It probably makes sense to disable dumping arguments by default.

Agreed.

**Comment by jonasdt** [comment] 2016-03-16 21:49
> That only works if you dump all your code in your application, but does not work if you have a heavily componentized system.

If you don't have a common namespace, then you can do something like

```php
$handler->setApplicationNamespaces(['Component1\\', 'Component2\\', 'Component3\\', ...]);
```

**Comment by jonasdt** [comment] 2016-03-16 23:00
Instead of disabling dumping of arguments entirely, we can also cut all internals of the dumped objects (i.e. only show the classname) by default.

@patroniton and @pelim 
Can you try my pull request #402? You can include the following lines in your composer.json file

```json
    "repositories": [{
        "type": "vcs",
        "url": "https://github.com/jonasdt/whoops"
    }],
    "require": {
        "filp/whoops": "dev-cut-internals"
    },
```

I've tried it for some of my Laravel projects and performance is fine.

**Comment by rossbearman** [comment] 2016-04-05 18:31
@jonasdt, your later pull request, #404, makes a dramatic improvement for me, using Whoops in Laravel 5.2. The average load time for the Whoops handler has gone from hovering at around the one minute mark to less than a second.

Without this change Whoops 2 is unusable for me and Whoops 1 doesn't work with PHP 7, so thanks for resolving that.

**Comment by denis-sokolov** [comment] 2016-04-05 18:47
Closed via #404. Will release soon.

@rossbearman, thank you for testing it.

**Closed by denis-sokolov** 2016-04-05 18:47 UTC

**Comment by vaites** [comment] 2017-08-28 11:31
I had this problem using PHP-FPM on Mac OS X, but works well with mod_php. Don't know if is caused by my configuration but switching to mod_php on my work machine solved the problem.

**Comment by staabm** [comment] 2017-08-28 11:52
please provide a blackfire (or similar) profiling result in case you are running out of memory/time

**Comment by vaites** [comment] 2017-11-11 22:59
@staabm, sorry for the delay. I was using a compiled version of PHP on Mac OS X 10.12. I had some strange segfaults so I discarded this installation method in favor of Homebrew and the problem dissapeared. Don't know what was the problem, but I think that maybe is related with those segfaults. 

Anyway, I tried to get some profiling but I can't because of the segfaults.
