### ISSUE TITLE
Syntax highlighting wrong when first line of snippet is the end of a block comment

### ISSUE THREAD

**Issue by CodeBrauer** [filp/whoops#385] opened 2016-02-15 16:52 UTC
![bildschirmfoto 2016-02-15 um 17 44 31](https://cloud.githubusercontent.com/assets/2059754/13054876/4af53c84-d40c-11e5-974e-d36c7f7ce947.png)

Line 22 is the end of a block comment and breaks the highlighting

**Comment by staabm** [comment] 2016-02-15 16:55
duplicate of https://github.com/filp/whoops/issues/214

**Comment by denis-sokolov** [comment] 2016-02-15 17:59
Thanks for the report! Thanks for the link, @staabm!

**Closed** 2016-02-15 17:59 UTC

**Comment by filips123** [comment] 2018-10-28 17:18
@acidjazz @denis-sokolov This still sometimes not work. See #588 and google/code-prettify#553 for details.
